---
- hosts: hw1
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
    - name: clone git repo
      git:
        repo: https://github.com/jso123450/cse356-cloud.git
        dest: /cse356-cloud/
    - name: move hw0.html into the document root
      copy:
        remote_src: yes
        src: /cse356-cloud/hw1/hw0.html
        dest: /var/www/html
        mode: preserve
    - name: remove local cloned copy
      command: rm -rf /cse356-cloud/
