HOST = 'localhost'
EXCHANGE = 'hw3'
EXCHANGE_TYPE = 'direct'
QUEUE = 'queue'
ENCODING = 'utf-8'

# main.py
JSON_KEY_STATUS = 'status'
JSON_KEY_KEY = 'key'
JSON_KEY_KEYS = 'keys'
JSON_KEY_MSG = 'msg'
JSON_VAL_ERR = 'ERROR'
JSON_VAL_OK = 'OK'

STATUS_ERR = {}
STATUS_ERR[JSON_KEY_STATUS] = JSON_VAL_ERR

STATUS_OK = {}
STATUS_OK[JSON_KEY_STATUS] = JSON_VAL_OK